if strcmp(computer, 'PCWIN')

mex -D__SUGAR_MEX ...
       sugar_c.c ...
       mempool.c shash.c symbol.c ...
       sugar.tab.c lex.yy-win.c ...
       parse.c codegen.c codestack.c evalexpr.c intrinsic.c ...
       codeprint.c codemx.c position.c varassign.c modelmgr.c ...
       paramprint.c assembly.c

% !copy sugar_c.dll ..\analysis

else

mex -D__SUGAR_MEX ...
       sugar_c.c ...
       mempool.c shash.c symbol.c ...
       sugar.tab.c lex.yy-win.c ...
       parse.c codegen.c codestack.c evalexpr.c intrinsic.c ...
       codeprint.c codemx.c position.c varassign.c modelmgr.c ...
       paramprint.c assembly.c

% !cp sugar_c.mex* ..\analysis

end
